name: svgaplayer_flutter
description: The SVGAPlayer implementation of Flutter using CustomPainter.
version: 2.2.1
homepage: https://github.com/gohopo/SVGAPlayer-Flutter

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  protobuf: ^2.0.0
  http: ^1.2.2
  path_drawing: ^1.0.0
  archive: ^3.1.2
